--------------------------------------------------------
--  FH Anwesenheitssystem Datenbank Tabellen löschen   
--------------------------------------------------------

DROP TABLE PERSON CASCADE CONSTRAINTS;
DROP TABLE PERSONAL CASCADE CONSTRAINTS;
DROP TABLE PERSONENRANG CASCADE CONSTRAINTS;
DROP TABLE STUDENT CASCADE CONSTRAINTS;
DROP TABLE STUDIENGANG CASCADE CONSTRAINTS;
DROP TABLE LVA CASCADE CONSTRAINTS;
DROP TABLE LVA_EINHEIT CASCADE CONSTRAINTS;
DROP TABLE KREUZERL_LISTE CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE LEITET CASCADE CONSTRAINTS;
DROP TABLE KREUZT CASCADE CONSTRAINTS;
